#!/bin/sh

WT_HEIGHT=18
WT_WIDTH=44
WT_MENU_HEIGHT=8

do_about() {
  whiptail --msgbox "\
PiGuard is an open source project by Neighborhood Guard an Oakland, CA Based non-profit
piguard-menu is written by Jesper Jurcenoks
Copyright 2014 Neighborhood Guard
Released under GNU Affero 3.0
www.neighborhoodguard.org
 \
" 17 44 1
}

do_shutdown() {
  sudo shutdown -h now

}

do_reboot() {
  sudo reboot
}

do_get_wifi_ip() {
  IP_ADDR=$(ifconfig wlan0 | awk '/addr:/ {print $2;}')
  whiptail --title "WI-FI IP address" --msgbox $IP_ADDR 7 36

}

do_ping_camera() {

  PINGRESULT=$(ping -c 4 -W 1 192.168.2.13)
#  PINGRESULT=$(ping -c 4 -W 1 10.19.12.2)
  whiptail --title "Ping Camera Result" --msgbox "$PINGRESULT" 17 48
}

do_update_piguard_menu() {

  sudo wget https://raw.githubusercontent.com/JesperJurcenoks/piguard-menu/master/piguard-menu -O /usr/local/bin/piguard-menu
  sudo chmod +x /usr/local/bin/piguard-menu
  
}


do_maintenance_menu() {

    while true; do
      SELECTION=$(whiptail --title "PiGuard Menu (piguard-menu)" --menu "Maintenance Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
        "1 Update PiGuard Menu " "" \
        3>&1 1>&2 2>&3)
      RET=$?
      if [ $RET -eq 1 ]; then
        do_finish
      elif [ $RET -eq 0 ]; then
        case "$SELECTION" in
          1\ *) do_update_piguard_menu ;;
          *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
        esac || whiptail --msgbox "There was an error running option $SELECTION" 20 60 1
      else
        exit 1
      fi
    done

}




#
#interactive use loop
#

while true; do
  SELECTION=$(whiptail --title "PiGuard Menu (piguard-menu)" --menu "menu Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
    "1 Get Wifi IP Address " "" \
    "2 Ping camera" "" \
    "3 Maintenance menu" "" \
    "7 Restart (Reboot) PiGuard" "" \
    "8 Shutdown PiGuard safely" "" \
    "9 About PiGuard-Config" "" \
    3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 1 ]; then
    do_finish
  elif [ $RET -eq 0 ]; then
    case "$SELECTION" in
      1\ *) do_get_wifi_ip ;;
      2\ *) do_ping_camera ;;
      3\ *) do_maintainance_menu;;
      7\ *) do_reboot ;;
      8\ *) do_shutdown;;
      9\ *) do_about ;;
      *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
    esac || whiptail --msgbox "There was an error running option $SELECTION" 20 60 1
  else
    exit 1
  fi
done
